### ISSUE TITLE
一个报错信息

### ISSUE THREAD

**Issue by moonlord09** [aooiuu/any-reader#11]
运行命令 any-reader.searchBookByRule 错误: Unexpected token '<', "<!doctype "... is not valid JSON。这可能是由提交 any-reader.searchBookByRule 的扩展引起的。

eso：
"eso://冰 灌溉机:笔趣阁api@H4sIAGjAOmIA/62cb2/b1hWHv8qm+pVhSRZJSZ6wbitaYFjR7UWSvpo6gJZoibFMCiKVxI092HHtpWniP6ibZoOzZk3reI2bKE2b2lHSfZfVFOVX+wq75CVlyvS9OpfHaFBEl38e8jwkpV/uAa+n9GqqlFImK4UZVZtMT6tFOa0Uqkp6WstNpQu5QlWStEIxJ6mpiVSlpam2dkmf01KlXEEpFqcKUqFYkKekyamJ1JxZ1Wd0rXqyfEpSJCknF6empOJESjPU6Yb2frNhqoRpt9raREpt23WzRY7AWev8wl2+3Xv5cW/nJUE1Tcu+WGnpTZssJJ8N1dtpyt3f7r94eHxvWW3qZLRO1iKjddtuWqVs1rDMX0mZa5Y6o9lapZ6pmHNkpVrLbDfpXiqmYWuGfWm+6R3hRMoyW2T73OTkpJKfSLUt7e3WfNM2372YKs2oDYscoHew71p0a7K89VaNbE8/0vN5R7cq5hWtFZ5RNfj8fqvhndbqnvt6y/nqkbvybW93p1TiHGq2UjWyDX26pbbms5W6ahha44JqzL6nW3ZWztZNOzvWVGtapm7PNcpG/8Xq0cuXvc62+91PzqfLmF1fMW1taN//vb9Ejvx4Zc+5ueY+65KPpZK7/pFz2O3tLJFTGQ2rkAulZhJaK8TkyH9qW29pWbXRgNN6dztJadd0w6q3BXD9px+RsaS4pm7UZjRDgOc8ue12P03Ku6oal3VYNXvf7h799ADjThJwN6AldieJuKM4jDtJyB3lYdxJIu6OV147Bzcw7mQBdwNaYneyiDuKw7iThdxRHsadLOLOWV9zNr7DuFME3A1oid0pIu4oDuNOEXJHeRh3iog799EW8vsuL/J9F9ISu8sLfd/5OIy7vNj3nc/DuMsLuXu91Ts4wLgriLgLaYndFYTc+TiMu4KYO5+HcVcQemZ+/dzd/gLjrijyzAxpid0VhZ6ZPg7jrij2zPR5GHdFIXebt71MgrnvRG68AS75jSd051Ee6s4Tu/UoEHXr8e49d/tHcnUcHXSPv7yHyXi2WrMGcZKk6eyHvkIwTUxfjBYYhOGE7cVwdlu/rKsGkCcsL8YL/I3CJcx4p3A5oLuEGS9GA7pLmPFiOKi7hBkvxoO6Iz8fbm44t/Z6rx5jDUpQg8NMlEcJ7DECxdqU4DYjVKxTCez0xr57dwtrU4HaDGkojwrYo4/DGlTgBn0e1p0Cdee8ftZ/tOZ0NvpPv8cazAMNnmKiPOahHqNQrM082GaUinWaBztd/cFd/wRrswC1GdJQHgtgjz4Oa7AAN+jzsO4KUHf91cPjLvpZWgS6G9BQ7opQdxSHdVcEu6M8rLsi1J37vOt2xfP8MC4HzhQhDeMuB88UPg7pLieQKXwe0l0OnCncf/+n/+IW1h00UwxoKHfgTEFxWHfwTEF5WHfgTOF+/c/+s2+w7qBpYkBDuQPnCIrDuoMnCMrDuoNnh/U9d3MN606GZoeQhnIng7ODj8O6k+HZwedh3clgd/e+OP77KtYdOPeFNJQ7eO7zcVh3ArnP52HdgXOfu/yD80p8rv0UDpr4BjSUO3DWozisO3jKozysO3C+o7jBkt7ujnPnM3/J+fVcjbpmektdUJfXWf9SH/7CBf07fZS5cxPNnDMNuy5Edbb20NSrmjYrdBXhyisyDxKFouobQEUKTLG4AgdYgQqTb8n+nU1chcMng8AlTKmoEodUoYvY5+JqHHJFiny3c3S4iysye76SD0XVOIAKldjH4kocYAUqTL/ecBXmzNDyqagSh1SRGlMursYhV+Qy3n7R/3wDV2SrbrYrqlETuZApFlXlAVboUvbBuDIPwGfVmbZpDM0dd466D/t7S70VbJSQGFFiFBPzo1RiBQouFPnTVGLGCi4V+QNVYoWLGNTZ+OrcnDIixigmyikraHChWKfMuMGlYp2yQkccetjtrTw/H6eM6YlRTJRT1iQFF4p1ypyq4FKxTlkTFvGHQ7LG31O4KehTN1njb4wGfd4ma/yN4cBP2mSNvzEe1N36J87uCtKdzJhsYtMw7mTWZBMDh3QnMyebGDykO5k12RTD9Z99c/z5HvlV2X+4jDXImHIaxUR5ZE08caFYm8zpJy4V65Q1CRW/hP7xN2dzHWuTMQnFpqE8siahGDisQeYkFIOHdceahIpfMJu3nSf3se4Yk1BsGsodaxKKgcO6Y05CMXhYd6xJqPgPp9V98gnrDpocBzSUO3BmpDisO3hapDysO3BOPJdmJxmaEM+l2UkGZ8NzaXaS4anwXJqdZHgefPLA2UXfd4wmQzYN5Y7VZMjAYd0xmwwZPKw7VpNhHPf4X2QM6w6c4kMayh08v/s4rDuB5O7zsO4EMvsdd7uDdQfP7AEN5U4gs3s4rDuRzO7xsO7gmX17h9zpSHcKOLOHNIw7BZ7ZfRzSnSKQ2X0e0p3Cz+yR1oqou+TzQRKv+YHPTDwZJPGbH7jU5DNBErf5gQHFNj9I3OYHPhRVX17zAxeLKzCn+YGlFdn8IPGbH/hUVIm5zQ9cLq7GvOYHFhbZ/CBxmx/4UFSNec0PXCyuxJzmBwYV2/wg8Zsf+FRUibnND1wursa85geWWmTzgzSi+YGPRVWZ3/zABePKzGp+SJ28L+9P2jWbvjMvMvgHW5uzhoe8fZKRsUymQf725/EPIssukV8x/rLwKKL7py8QHMv4bxI8GX+bvryPLNArphFZ8Fb4asKxTPCWwshGdbVp+5tFBt/RLP+FhTrZjbdVNfL5ZK0LmtVu0DPQq4O3CF7U1FalHr5D0PI/0WrwCq429UHB03Sj33qn9+bYrDZ/1Wx5+6fDQ9WlQ5Ha0oGzKkuXnFXXYL+nqkpHYzWlw2dVNNggWk86xK8mXefsWv6RjOkXTLVqhfWs0N0HY2Ttlr+hf56pocWnzydYNFqFd+1Pm+ZsNtjCv/THAk5wqQeLhlwEYxEZkR34RzJ8kIwDDCse2d6szA4N0NdyRgYG1YOdF311Zvb69d9dtkoN1bLp9ouLZMir/+Li4DzpqifnSD8PnzcdC8+bXHTByBtv/PqX6XTNTKd/s+DcWSF/MuM0rbmPH/Rv3fjfq+UFbw3vhL11PrQnf7+QGXf398n/Hj/IjC+Uy391uxvl8l/IH6dD/kI26T/9vlz+eWV/4Xj3rrOxVS5/sNDrHBwdrnpv57y/lBnvP/3R/fjL/pMOWTnlvfazphuRgzVndS3wc0XXrl605xukmJOL/wdwO94zQFUAAA==",

**Comment by aooiuu** [comment]
域名没法访问
