### ISSUE TITLE
[Bug] windows7电脑的VSCode插件无法运行

### ISSUE THREAD

**Issue by oneWayOut** [aooiuu/any-reader#139]
### 在哪个平台出现的问题?

VSCode

### 问题描述

windows7电脑的VSCode 1.70.3 上安装v1.10.10 any-reader后，插件状态无法正常显示（见图1）， 
![图1](https://github.com/user-attachments/assets/85ce3f09-61ed-4405-9304-7c5dd61579f3)

Ctrl+Shift+P 命令中选择any-reader 打开文件 后出错（见图2）；
![图2](https://github.com/user-attachments/assets/860bd355-6be9-4679-8cca-9b3d2af522f5)

**Comment by aooiuu** [comment]
如果可以的话，升级下 vscode 版本试试

**Comment by aooiuu** [comment]
这个版本的 webview 似乎有点问题， 我发现一些使用了 webview 的扩展也无法运行

**Comment by Clarice0997** [comment]
VSCode 是 Electron 开发的，Electron 22 后就弃用了 Windows 7 支持了，可能和这有关系

**Comment by aooiuu** [comment]
> VSCode 是 Electron 开发的，Electron 22 后就弃用了 Windows 7 支持了，可能和这有关系

才发现 v1.70.3 确实是 vscode 最后一个支持 win7 的版本的

**Comment by oneWayOut** [comment]
好的，谢谢
