### ISSUE TITLE
样式不对，左侧菜单文字看不清，该怎么调整

### ISSUE THREAD

**Issue by ddq1971130532** [aooiuu/any-reader#15]
![image](https://github.com/aooiuu/any-reader/assets/51527118/3007381a-c260-4515-a48b-a313eb7813b9)

**Comment by aooiuu** [comment]
请问您用的是什么颜色主题？

这部分颜色目前是计划自适应 `vscode` 颜色主题的，这里颜色不对，可能是因为我的变量没用对

**Comment by aooiuu** [comment]
目前做了简单的适配，但是不同主题颜色效果不一致。

欢迎大佬们继续完善颜色主题

https://github.com/aooiuu/any-reader/blob/master/packages/web/src/assets/main.scss

**Comment by ddq1971130532** [comment]
![image](https://github.com/aooiuu/any-reader/assets/51527118/1f873de7-e98b-411d-83ff-387f4b048821)
原来如此，更新后换了个主题就好了，感谢作者

> 请问您用的是什么颜色主题？
> 
> 这部分颜色目前是计划自适应 `vscode` 颜色主题的，这里颜色不对，可能是因为我的变量没用对
