### ISSUE TITLE
[需求] 在控制台里查看书籍

### ISSUE THREAD

**Issue by taoozi** [aooiuu/any-reader#154]
### 功能描述

要是可以在VScode控制台里查看epub或者pdf就更好了

**Comment by aooiuu** [comment]
VSCode 插件窗口是可以拖动到控制台的。

![image](https://github.com/user-attachments/assets/01deecb5-09f5-4c0d-af7e-e73ba17698ce)

**Comment by taoozi** [comment]
那我现在可以先将pdf转为epub进行阅读了，多谢！！！
