### ISSUE TITLE
[需求] 增加全局常用快捷键

### ISSUE THREAD

**Issue by littleRudeBull** [aooiuu/any-reader#159]
### 功能描述

希望增加激活any-reader为当前的全局快捷键，类似无论何时均可按下终端的快捷键 ctrl+` 将终端置为当前；
增加 上一章、下一章、上一页、下一页的快捷键

**Comment by aooiuu** [comment]
目前是有上一章、下一章、上一页、下一页的快捷键的，不过是需要聚焦阅读页。

这4个快捷键是有什么使用场景需要注册到vscode全局吗？

**Comment by littleRudeBull** [comment]
上一章、下一章、上一页、下一页 快捷键不需要全局，我前面进设置页面没注意到

**Comment by littleRudeBull** [comment]
不过建议 快捷键 下一页 能 支持空格为键值，习惯上还是以空格作为翻页
