### ISSUE TITLE
支持侧边栏阅读

### ISSUE THREAD

**Issue by aooiuu** [aooiuu/any-reader#16]
为了增加隐蔽性, 目前考虑到两个方案。

1.底部状态栏阅读
2.侧边栏阅读

侧边栏阅读具有以下优势
1.文字更多
2.可以拖动到其他位置，比如底部、侧栏

![image](https://github.com/aooiuu/any-reader/assets/28108111/b228bd28-40d4-42b9-a52e-db11a9690b7d)

**Comment by WeizhenEricFang** [comment]
不小心隐藏了，怎么重新打开
