### ISSUE TITLE
增加自定义header头

### ISSUE THREAD

**Issue by dxkrs** [aooiuu/any-reader#18]
规则中有userAgent字段，但不生效，查看源码原来是固定值。。。（那Cookie字段也是预设？）
建议可以自定义header头请求，现很多网站都有防御，最好能让请求尽可能地模仿模拟器请求。

**Comment by aooiuu** [comment]
https://aooiuu.github.io/any-reader/rule/#url-%E8%A7%84%E5%88%99


`Cookie` 字段目前我还没有支持

`header` 目前感觉可以直接用 `@js:(() => { return {url, method, body, encoding, headers}; })();` 这种JS规则去写。(理论上支持)
