### ISSUE TITLE
书源编辑问题

### ISSUE THREAD

**Issue by 3492726416** [aooiuu/any-reader#21]
![image](https://github.com/aooiuu/any-reader/assets/130670046/68818bce-5c0d-44b2-8aee-163b4a6ecc8e)
您好，请问一下这两个JSON是一致的吗，为什么配置右边那个.json左边的不发生变化，而且配置好左边JSON后确定后等待了很久也没有配置好，又回归了默认状态
![image](https://github.com/aooiuu/any-reader/assets/130670046/47bbff09-d69c-4c9a-9b77-9f772833736e)

**Comment by aooiuu** [comment]
是一致的
理论会同步更新显示, 我刚测试的会同步更新的

json部分字段比较多，有的字段表单没有。

规则新增有bug.  建议先直接修改源文件。

**Comment by aooiuu** [comment]
在 vscode 插件内修改规则会实时同步到 `book-source.json`
在 `book-source.json` 修改规则不会实时同步到 vscode 插件 

也就是说目前只是单向同步的

1. 点击侧边栏的刷新按钮 会刷新侧边栏的规则
2. 重新打开 webview 面板，会刷新 webview 面板内的规则

**Comment by 3492726416** [comment]
如何删除没用的源？
![image](https://github.com/aooiuu/any-reader/assets/130670046/fc473fe3-8ae2-494c-9f49-2ad310dca99b)

**Comment by aooiuu** [comment]
等晚上更新个新版

**Comment by aooiuu** [comment]
![image](https://github.com/aooiuu/any-reader/assets/28108111/5428da37-bd3f-40eb-a06f-64afc9068940)

已更新删除功能

**Comment by 3492726416** [comment]
哎呀😣😣😣配置了好久还是没弄好，我还是先用你之前做的那个z-reader吧🥱🥱🥱

**Comment by aooiuu** [comment]
会越来越好的。可以加群。

**Comment by yuanhongyu123** [comment]
> 会越来越好的。可以加群。

群号多少啊

**Comment by aooiuu** [comment]
> 群号多少啊

QQ群: 50057637 @yuanhongyu123
