### ISSUE TITLE
构建镜像失败。

### ISSUE THREAD

**Issue by kokojacket** [aooiuu/any-reader#22]
构建镜像失败
`[koko@koko-464c2 any-reader]$ sudo docker build -t any-reader .

Password: 

Sending build context to Docker daemon  1.163MB

Error response from daemon: dockerfile parse error line 18: Unknown flag: parents

[koko@koko-464c2 any-reader]$ `

**Comment by aooiuu** [comment]
看起来和 Docker 版本有关

错误在：`COPY --parents packages/*/package.json /app/`

不支持 ` --parents `

https://docs.docker.com/reference/dockerfile/#syntax

Not yet available in stable syntax, use [docker/dockerfile:1.7-labs](https://docs.docker.com/reference/dockerfile/#syntax) version.

晚点我换成常规语法

**Comment by kokojacket** [comment]
大佬是否可以直接推送一个到dockerhub，求~
