### ISSUE TITLE
源信息相关

### ISSUE THREAD

**Issue by msp233** [aooiuu/any-reader#30]
1. 源信息现在好像是存在浏览器中的，我同一台电脑，不同浏览器访问都不一样。新浏览器要重新导入源信息，不然打开是空白的。我当时是先后在两台电脑登录，发现第二台电脑没有之前导入的源信息，推测源信息没有保存在服务端共享，是在客户端存在，然后重新导入源信息，换了个浏览器复现一下，果然登录后新浏览器也没有源信息。（还是说有什么保存按钮，才能全局生效，我没找到类似的按钮）

2. 无论是源信息和账号绑定到一起（不同账号用不同的源），还是不同账号用同一个源（都希望源存在服务端）

**Comment by msp233** [comment]
对了，我用的是这个，不是latest，
![image](https://github.com/aooiuu/any-reader/assets/20732887/a2d37d78-6218-4ce2-b5fc-2a0d25ce1b4c)

**Comment by aooiuu** [comment]
1.源信息是在服务端的，不是在浏览器

> 登录后新浏览器也没有源信息

这是个 bug. 已修复
