### ISSUE TITLE
能改背景色和字体颜色吗，而且历史记录为什么不会自动保存

### ISSUE THREAD

**Issue by Yep0578** [aooiuu/any-reader#32]
能改背景色和字体颜色吗，而且历史记录为什么不会自动保存

**Comment by aooiuu** [comment]
vscode 背景颜色是适应 vscode 主题的, 字体大小、行高、间距在设置里。
桌面端、网页端的背景颜色和字体颜色在 [设置] -> [阅读页] 里面

历史记录某个版本更新后重构删掉了。计划后面一两个版本内更新回来

**Comment by Patrick-Ze** [comment]
@aooiuu 没有自适应vscode主题，我使用的是VS Code内置的Light+主题，效果如下，几乎不可见
![image](https://github.com/aooiuu/any-reader/assets/19711799/761175fe-4bf0-4a2c-8e32-f6add9f90e44)
VS Code版本
```
Version: 1.91.0 (user setup)
Commit: ea1445cc7016315d0f5728f8e8b12a45dc0a7286
Date: 2024-07-01T18:52:22.949Z
Electron: 29.4.0
ElectronBuildId: 9728852
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.19045
```
