### ISSUE TITLE
[Bug]: ESO能用 插件不能用

### ISSUE THREAD

**Issue by DuJiaHui123** [aooiuu/any-reader#34]
### 在哪个平台出现的问题?

VSCode

### 问题描述

ESO能用 插件不能用

### 请描述BUG产生过程

eso://:测试用@H4sIAHyfi2YA/22RzW7TQBDHXyVaOLSSk7XjuHYiNQSVC4hyaNpTGqH17rhesfaa3XFcC/EEXOEduHHilYDHYN3Y5kO9rGZn/jO/+fhApCArcpaEy3TJ+DQSEZ8u4pRPE55l0zCO4yjNltEi8IlHuAGGcC0LIKsgnvuLeZQkkT9PnMAjhRYykyD+jp8FYeh3mtgjULJUwU2lNHNMNDV4pGSdlvz4/unXty8/P391kFxbdK4csVpR2jTNjKU8le/rO5hxXXRt6BKhxOu26jgesdq4jMD3/YXD1BYuTFuhfrUlq4wpCwP6hbRcH8D8594CMzwfOrIPvxujXA/UjVQrsJQZlFwBPQZnVV49O5rvoD1/6p5GG0GG5NfyYQJKsSu/23DFrD2/JXdGiluyp5hq0VI0u0pbiVKXJ6frYD+mvznuxKWLXbCnjCLc48npGH9eY67NoAgfUVzkrEIYJfNHJFdga4X/YDa5gYwMW7l0YXnlTmXHdfFj2X68Warv37pTTNYTIQ/dqyZrIZzByKjtZ+ngf5wjuwf293yJUDgYedL/NzkWyoUPEpottsoV8j/+BnyAWsixAgAA

**Comment by aooiuu** [comment]
https://github.com/aooiuu/any-reader/issues/36
