### ISSUE TITLE
导入eso书源后，点击搜索报错

### ISSUE THREAD

**Issue by yuanhongyu123** [aooiuu/any-reader#4]
运行命令 any-reader.searchBook 错误: cheerio.load() expects a string。这可能是由提交 any-reader.searchBook 的扩展引起的。

这是书源json：
[
  "eso://:笔趣阁@H4sIABVrLWIA/3VVy27TQBTdV+o/WE5VJaSxncQmD9Q0Vbuh4iG1ZYVZTMZjexrb486MSaOmEuxZIoQEO5awYIFYIfE1FFjxC0wc26kfiRTLOeee65l7jifX21uS+MjYkoeSbOv3AbIH3ZZu9Y2Wbhio1dd02NI7g44xQYNeVzPkvUQCKQIcnWMfCWnbGLQ1Te9rWr+vGbqRFvnEwjZGVq5s0Gt3e0ano3fTMhBxl9DlErL2IWH8DFIc8hwcgLiR/PvL2z/fP/19/zpjXCFYMi7nIRuq6mw2U64m+DJykAJhVuZQEoW5lpAEHAX8fB7GS0xhRuiyn5b+jhg6ovOQk5MzAdvAYyilPAKsE5ZrKqrpoSPa5lAUgImHjjGD5CWixTZWgj+jXk6V4g858lkl8wgzXkmcA6da8SSZY4k4SlZWZg7LJmUiF4R8g+wYsdhGTIJK/hSxyKsa0xkCFLqC4DTKZsRiMJnQtSlH1DPlobnBdVXkL/IQUwHlGHpIXcmV0A0PVrdTNN/fEZcZodZuCBy0v7O8mvKeKZYBRXwDJ36AM5ma8o2cX0fZkRWe+lHzAQ5GSiD26TFPgIyNPLxYTIg1L0hSpxTWHnN0xQt06pfCOjG9WLiVdZl9NdvHviOJ75hRWKhaW6kwPelXw4FNRuEw4G4Lutiz6t1G5RPWXiusu1HcrxQXwiBknJK4cHdXYUZ216sSr5MipiCBsUuRLR6d2+j4gg1pXKfgwEJXT+26KWM/trQxarUPpI1ZmRAyVU1ZkppJAx9w6NbVumlazQZTLkJHbTxvv2iasigbSquqB4XUPhYYPhUHAiu+3nA1uJS7cwCtidJrmXDFIyGBy/lLiCyAy9BJliWBYkX6pNycE658BqRtCZxW4cnxXt5S5tjSq6U3E8CQ2Ewy4uIZXNrmCs62WUuAOB21WvYnIOWt/Pfjze3HV79+fr798O323Vfl3p1UXBAciEiINCgs9DCvq6bJmqrTkLe3bv4Dy+SK7g8HAAA="
]

**Comment by aooiuu** [comment]
`encoding` 规则尚未实现

![image](https://github.com/aooiuu/any-reader/assets/28108111/3e3c5f0f-51a9-45e8-a780-ee7de1f713fe)

![image](https://github.com/aooiuu/any-reader/assets/28108111/1265db3a-c8e6-4946-91b9-989f55f127f4)
