### ISSUE TITLE
可以提供一个可用的书源吗

### ISSUE THREAD

**Issue by linyuanxy** [aooiuu/any-reader#5]
找不到可用书源了

**Comment by aooiuu** [comment]
抱歉! 出于版权考虑, 目前没有公开源的计划。

但 `any-reader` 依然在积极更新，以避免用户卡在使用的第一个环节。

[文档](https://aooiuu.github.io/any-reader/rule/)

**Comment by bill-mark** [comment]
不能来个小号下面评论给吗  99%的用户卡在第一步了

**Comment by aooiuu** [comment]
新版本已经支持多源聚合搜索了。

`any-reader` 和拥有海量规则的 `eso` 的规则规范一致

**Comment by fmnijk** [comment]
https://github.com/aooiuu/z-reader/issues/163
看懂怎麼用了
反正就是要編輯這個文件加入eso源就是了
%userprofile%\\.any-reader\book-source.json

我還遇到一個問題是
book-source.json
favorites.json
history.json
這三個文件都是空白的，第一次使用會報錯，我手動加了括號
```
[
]

```
才好的，不然會出現像是favorites.json: Unexpected end of JSON input的錯誤

插件使用方法就是點這些按鈕，三個文件都要加括號，插件重啟後按鈕點了才有反應
![Screenshot 2024-03-30 05-48-06](https://github.com/aooiuu/any-reader/assets/52465927/88b41a65-7667-487c-a5c9-d85feb01b3d0)

**Comment by aooiuu** [comment]
> 我還遇到一個問題是 book-source.json favorites.json history.json 這三個文件都是空白的，第一次使用會報錯，我手動加了括號


谢谢反馈, [v0.5.1 已修复这个问题](https://github.com/aooiuu/any-reader/commit/f226f50e93de0fc77b9dbf058ed9d04875122e4b)， 现在不用手动编辑这几个 json 文件了

**Comment by lzailqy** [comment]
卡在使用的第一个环节，哪里去找源

**Comment by ccdyy** [comment]
折腾了一下，没啥书源，还是回到z-reader了

**Comment by ocean520x** [comment]
![Snipaste_2024-04-22_11-55-07](https://github.com/aooiuu/any-reader/assets/113085440/33ce014d-2531-4731-89c2-ecbe344c56f8)
请问下 配置完eso之后搜索为什么会出现此问题 如何解决呢？

**Comment by aooiuu** [comment]
> 请问下 配置完eso之后搜索为什么会出现此问题 如何解决呢？

源不支持，可以忽略此错误
建议先用聚合搜索，挑选出可用的源
