### ISSUE TITLE
不支持阅读本地书籍吗？

### ISSUE THREAD

**Issue by Ternurafl** [aooiuu/any-reader#7]
没有看到添加本地书籍的地方，是不支持阅读本地书籍吗

**Comment by aooiuu** [comment]
暂时没有，后续有计划支持

本地书籍有什么意见或者操作功能要求，欢迎大家在这里反馈。

**Comment by Ternurafl** [comment]
功能建议：
希望可以支持阅读本地文件夹中的.txt .epub等常见格式的电子书，功能的话建议可以实现目录跳转，字体缩放、阅读进展记忆，以及快捷键章节跳转、隐藏和显示（摸鱼专用），可以参考novel-look2这个插件，但是它貌似只支持txt格式的文件。
原因说明：
我个人感觉在vscode中看小说对应的应该是“摸鱼”的场景比较多，所以功能不用太花里胡哨，只需要能满足基本的阅读需求即可，用户更注重的应该是支持的文件类型能否覆盖他拥有的资源（txt epub azw3......），以及“隐蔽性”（支持快捷键跳转、隐藏、显示）。
最后：
期待本地阅读功能早日上线，同时也感谢大佬的不吝开源，让我在工作之余可以“偷得浮生半日闲”（手动抱拳~）

**Comment by mabDc** [comment]
简单的操作，
好像可以把文件夹当做一个源？于是可以搜索，可以发现，可以添加到书架
