### ISSUE TITLE
换行显示问题，以及一个报错信息！

### ISSUE THREAD

**Issue by hezlog** [aooiuu/any-reader#9]
![image](https://github.com/aooiuu/any-reader/assets/13940360/aa8b6503-795f-4c30-8218-ee87cbf0f61b)

1.显示内容换行不对劲。
2.点击章节时报错。
3.请求增加本地txt文档解析。

Actual command not found, wanted to execute any-reader.getContent /20

**Comment by hezlog** [comment]
另外一个异常是：
http is not defined

**Comment by aooiuu** [comment]
1、2.暂时可以先换个源， 或者后续看看有没有其它解决方案，正常情况下源返回的是有换行的
3.   https://github.com/aooiuu/any-reader/issues/7

**Comment by mabDc** [comment]
附议增加本地功能。
好像可以把文件夹当做一个源？于是可以搜索，可以发现，可以添加到书架
